### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Ehesp** [binggg/react-native-material-design-components#22]
As much as I like this project, I feel there's quite a bit which needs improving for it to be maintainable. Also, @binggg do you have time to manage this on your own? Anyway a list:
- [x] Support React 0.16 & Babel 6 - I have this working locally, https://github.com/binggg/mrn/pull/21 - however in my eyes the project should support 0.16.\* only in my eyes, since there's some big changes in it.
- [x] Have React Native 0.16 as a peer dependancy
- [x] Linting files with ESLint (https://github.com/binggg/mrn/issues/15) - Loads of inconsistencies, unused code etc.
- [ ] Fixing the Ripple state bug (https://github.com/binggg/mrn/issues/9)
- [ ] Tests - currently it's hard to make changes to components because I have no idea if the change will break something else.
- [ ] Documentation - Could do with some more examples/spell-checking etc
- [ ] Contributing Guidelines
- [x] Have `react-native-vector-icons` as a project dependancy
- [x] Break this project down into an organisation? Would be better to have multiple repositories in the same place, although this is @binggg's call.

Please provide feedback on these, this project is easily the best material one out there at the moment, just needs some loving.

**Comment by carbureted** [comment]
+1. I would love to see this project become bulletproof, and would also be willing to contribute to help make that happen.

**Comment by binggg** [comment]
I'm glad to hear that.
Very busy recently, I will consider your proposal, thank you for your enthusiasm

**Comment by Ehesp** [comment]
OK great, let us know what you want to do, plenty to get on with!

**Comment by mrcasals** [comment]
I can help too! :)

**Comment by Ehesp** [comment]
@binggg had anymore thought on this?

**Comment by vongkim** [comment]
+1 I would like to help too.

**Comment by Ehesp** [comment]
I think tomorrow I'm going to setup an organisation on here to continue this project, I need this stuff for work and there's plenty to do, @binggg if you've anything against this please let me know!

**Comment by binggg** [comment]
okay

**Comment by Ehesp** [comment]
An FYI - I've done the following:
- Cleaned up all of the components, using ESLint
- Fixed a bunch of issues
- Got it working with RN 0.16

There's a couple of things I've done differently like using the default font from react native vector icons which requires way less setup.

I'll make an org for this later, GitHub is telling me the one I made is suspicious...

**Comment by Ehesp** [comment]
I've pushed the initial repository up to:

https://github.com/material-react-native/mrn

It includes a variety of fixes and improvements, hopefully now it's on an organisation it'll be easier to manage!

**Comment by Ehesp** [comment]
@binggg What do you want me to do now? The repo has been setup and everything has been ported across with loads of bug fixes and cleanup.

However the problem I have now is that unless you want to keep the project as "mrn" then I cannot push it to NPM (and hence can't publicly use it).  The options are:
1. Delete the other organisation (I'll keep the code), and you change/push this one into a new organisation. This will keep the stars/followers/issues.
2. Deprecate this one with a link to the other organisation repo. This will lose all stars etc.
3. Push it up to NPM as a new package, and credit you in the README. Again will lose stars etc. 

Please let me know what you want to do ASAP so I can push it publicly.

**Comment by dgilperez** [comment]
Great effort! 

If I'm not mistaken, @binggg could promote this project to a new org, and then give @Ehesp commit permissions so he can cherry pick the new changes and release a new version. This way stars would be preserved and there should not be any issues with project name.

+1 on supporting only > 0.16. By the way, 0.17 is out!

**Comment by Ehesp** [comment]
@dgilperez Well I didn't get a response from binggg so I had to make it into my own NPM lib. I've done a ton more work on it and will probably be pushing it all tomorrow. Working well on my device right now.

**Comment by satvikmaker** [comment]
WOW @Ehesp Amazing work! Really appreciate it and would like to contribute. And thanks @binggg for the initial effort for working on this.

**Comment by efkan** [comment]
Is there any plan designing Cards like [this](https://github.com/xinthink/react-native-material-kit#cards) ?

**Comment by Ehesp** [comment]
@efkan Done here: https://github.com/react-native-material-design/react-native-material-design

**Comment by efkan** [comment]
OK. This is awesome :)
Thanks!

**Comment by binggg** [comment]
Guys, I have been busy with my new job and my wedding, it seems I left behind many, I have to catch up with it

**Comment by efkan** [comment]
Is there any chance to convert [Material Design Lite components](http://www.getmdl.io/components/index.html) into React-Native and import to MRN ?
